name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Decode fcm.json
        env:
          FIREBASE_SECRET: ${{ secrets.FCM }}
        run: echo $FCM > ./src/fcm.json

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build
